version: 2
updates:
  - package-ecosystem: "npm"
    directory: "./webhook-collector"
    schedule:
      interval: "weekly"
    groups:
      npm-deps:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
          - "*"
