{
 "title": "Workflows - Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "org",
    "label": "Org",
    "query": "{\"find\": \"terms\", \"field\": \"organization.login.keyword\", \"size\": 1000}"
   },
   {
    "name": "repo",
    "label": "Repo",
    "query": "{\"find\": \"terms\", \"field\": \"repository.name.keyword\", \"size\": 1000}"
   },
   {
    "name": "runner_group",
    "label": "Runner Group",
    "query": "{\"find\": \"terms\", \"field\": \"workflow_job.runner_group_name.keyword\", \"size\": 1000}"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "workflow_job.id", "id": "1", "type": "cardinality" }
     ],
     "query": "organization.login:${org} AND repository.name:${repo} AND workflow_job.runner_group_name:${runner_group}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Jobs over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "workflow_job.id", "id": "1", "type": "cardinality" }
     ],
     "query": "organization.login:${org} AND repository.name:${repo}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Labels",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "workflow_job.labels.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "workflow_job.id", "id": "1", "type": "cardinality" }
     ],
     "query": "organization.login:${org} AND repository.name:${repo}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Runner Groups",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "workflow_job.runner_group_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "organization.login:${org} AND repository.name:${repo}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Runs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "workflow_run.id", "id": "1", "type": "cardinality" }
     ],
     "query": "organization.login:${org} AND repository.name:${repo}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Runs over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "workflow_run.id", "id": "1", "type": "cardinality" }
     ],
     "query": "organization.login:${org} AND repository.name:${repo}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Runs By Repo",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "repository.full_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Conclusions",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "workflow_job.conclusion.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "organization.login:${org} AND repository.name:${repo}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Job Conclusions Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "workflow_job.conclusion.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "4", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "workflow_job.id", "id": "1", "type": "cardinality" }
     ],
     "query": "organization.login:${org} AND repository.name:${repo}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Jobs By Repo",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "repository.full_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Avg Run Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "duration", "id": "3", "type": "avg" }
     ],
     "query": "organization.login:${org} AND repository.name:${repo}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Run Durations over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 20 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "duration", "id": "1", "type": "max" },
      { "field": "duration", "id": "4", "type": "min" },
      { "field": "duration", "id": "5", "type": "avg" }
     ],
     "query": "organization.login:${org} AND repository.name:${repo}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Runs by Duration",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 20 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "workflow.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "duration", "id": "1", "type": "max" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Avg Queue Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "queue_duration", "id": "3", "type": "avg" }
     ],
     "query": "organization.login:${org} AND repository.name:${repo}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Queue Durations over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 26 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "queue_duration", "id": "1", "type": "max" },
      { "field": "queue_duration", "id": "3", "type": "avg" },
      { "field": "queue_duration", "id": "4", "type": "min" }
     ],
     "query": "organization.login:${org} AND repository.name:${repo}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Jobs by Queue",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 26 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "workflow_job.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "queue_duration", "id": "1", "type": "max" }
     ],
     "query": "action == 'completed'",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Avg Job Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "duration", "id": "3", "type": "avg" }
     ],
     "query": "organization.login:${org} AND repository.name:${repo}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Job Durations over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 32 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "duration", "id": "1", "type": "max" },
      { "field": "duration", "id": "3", "type": "avg" },
      { "field": "duration", "id": "4", "type": "min" }
     ],
     "query": "organization.login:${org} AND repository.name:${repo}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Jobs by Duration",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 32 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "workflow_job.name.keyword",
       "id": "4",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "duration", "id": "1", "type": "max" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Avg Step Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "workflow_job.steps.duration", "id": "3", "type": "avg" }
     ],
     "query": "organization.login:${org} AND repository.name:${repo}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Step Durations over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 38 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "workflow_job.steps.duration", "id": "1", "type": "max" },
      { "field": "workflow_job.steps.duration", "id": "3", "type": "avg" },
      { "field": "workflow_job.steps.duration", "id": "4", "type": "min" }
     ],
     "query": "organization.login:${org} AND repository.name:${repo}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Steps by Duration",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 38 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "workflow_job.steps.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "workflow_job.steps.duration", "id": "1", "type": "max" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}