name: CI Grafana / OpenSearch

on:
  pull_request:
    paths:
      - 'grafana-opensearch/**'
      - '.github/workflows/ci-grafana-opensearch.yml'

permissions: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TARGET_TYPE: opensearch
      OPENSEARCH_HOST: opensearch-node1
      OPENSEARCH_PORT: 9200
      OPENSEARCH_PROTOCOL: 'https'
      OPENSEARCH_USERNAME: 'admin'
      OPENSEARCH_PASSWORD: 'ChangeMe123!'
      OPENSEARCH_VERSION: '2.14.0'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Compose Up
        run: docker-compose -f grafana-opensearch/docker-compose.yml up -d
      # - name: Check Grafana
      #   run: curl http://localhost:13000
      # - name: Check opensearch-dashboards
      #   run: curl -k https://localhost:5601
      # - name: Check webhook-collector
      #   run: curl http://localhost:3000
