name: CI Linting

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Super Linter
        uses: super-linter/super-linter@v6
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: false
          validate_all_codebase: true
          debug: false
          linter: 'eslint'
          eslint: 'true'
          eslint_args: '--ext .js,.ts,.tsx'
          eslint_ignore: 'node_modules'
          eslint_config: './webhook-collector/eslint.config.js'
          eslint_extensions: '.js,.ts,.tsx'
          eslint_glob: 'webhook-collector/**'
